services:
  postgres:
    image: postgres
    container_name: nx_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
